const jwt = require('jsonwebtoken')
const token = jwt.sign({ id: 'any_id' }, 'anySecret', { expiresIn: '2 days' })
console.log(token)
const accessToken = jwt.verify(`${token}`, 'anySecret')
console.log(accessToken)
